### ISSUE TITLE
멤버들이 static 으로 되어 있으면 안됩니다.

### ISSUE THREAD

**Issue by jslee0086** [dae0hwang/Second_Chatting_Project#4]
https://github.com/dae0hwang/Second_Chatting_Project/blob/2a1bd57a2776e170f2a747071893fef390946c02/Server/src/main/java/Header.java#L4

두명이상이 동시에 데이터를 전송할 경우 문제가 발생하게됩니다.

**Comment by dae0hwang** [comment]
수정했습니다.
