### ISSUE TITLE
형태가 약속된 Json 을 받기 때문에, 이런식으로 일일히 처리할 필요가 없습니다.

### ISSUE THREAD

**Issue by jslee0086** [dae0hwang/Second_Chatting_Project#7]
https://github.com/dae0hwang/Second_Chatting_Project/blob/7ba6e6ddf1b6c97155059049bfc2df318203b115/Client/src/main/java/SeverHandler.java#L37

**Comment by dae0hwang** [comment]
수정했습니다.
