### ISSUE TITLE
ReadUtf 는 이상합니다. Header 가 길이를 알고 있기 때문에 정확한 길이를 지정 해서 받아야 합니다

### ISSUE THREAD

**Issue by jslee0086** [dae0hwang/Second_Chatting_Project#8]
https://github.com/dae0hwang/Second_Chatting_Project/blob/7ba6e6ddf1b6c97155059049bfc2df318203b115/Client/src/main/java/SeverHandler.java#L36

**Comment by dae0hwang** [comment]
수정했습니다.
